# Generated by Django 4.2.4 on 2023-08-15 18:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("generic", "0007_remove_author_body_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(template="heading_block.html"),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
